IF DB_ID('fxDBdata') IS NOT NULL
    BEGIN
        ALTER DATABASE fxDBdata SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
        DROP DATABASE fxDBdata;
    END
    CREATE DATABASE fxDBdata;
	
IF DB_ID('fxDBwork') IS NOT NULL
    BEGIN
        ALTER DATABASE fxDBwork SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
        DROP DATABASE fxDBwork;
    END
    CREATE DATABASE fxDBwork;
	